// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqNmdPNqCeO-XMFdojcUv3ZBP_n2Dpupg',
    appId: '1:932352299074:web:f09c92b9fcbc07fcb51ddb',
    messagingSenderId: '932352299074',
    projectId: 'laporpungli-63fbe',
    authDomain: 'laporpungli-63fbe.firebaseapp.com',
    storageBucket: 'laporpungli-63fbe.firebasestorage.app',
    measurementId: 'G-CSHYN61P0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH9q8LqB5HMrQQuDEaFuEyrgSKJ8zao0Q',
    appId: '1:932352299074:android:2e3de04814de6281b51ddb',
    messagingSenderId: '932352299074',
    projectId: 'laporpungli-63fbe',
    storageBucket: 'laporpungli-63fbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF5HNCMjI0PFpvy5-Bc8dyeTqe8_LZjCw',
    appId: '1:932352299074:ios:6facd5995e255babb51ddb',
    messagingSenderId: '932352299074',
    projectId: 'laporpungli-63fbe',
    storageBucket: 'laporpungli-63fbe.firebasestorage.app',
    iosBundleId: 'com.example.laporPungli',
  );
}
